version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_tomcat
    ports:
      - "9999:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: toanthietkeweb
      DB_USER: dbdtoan
      DB_PASSWORD: password

  db:
    image: mysql:8.0
    container_name: my_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: toanthietkeweb
      MYSQL_USER: dbdtoan
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB/data.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

